### ISSUE TITLE
1.4.0 todo list

### ISSUE THREAD

**Issue by HavicDave** [iLexiconn/JurassiCraft#233]
- [x] Velociraptor no sound and cannot damage player when it attacks
- [x] Arsinoitherium no sound
- [x] Leptictidium no sound
- [x] Titanis  no sound
- [x] Tyrannosaurus cannot damage player when attacking
- [x] Herrerasaurus sound to low cannot attack player
- [x] Parasaurolophus hurt sound does not work
- [x] Carnotaurus sound to low cannot damage player
- [x] All creatures derp on security fence and die with it turned on will not move from the fence.
